### ISSUE TITLE
Feature Plan

### ISSUE THREAD

**Issue by KHarishDev** [KHarishDev/NekoRobot-3#19]
**Good News: We Are Going To Make PTB v20.0a2 Stable Soon As Possible**

**Comment by SOME-1HING** [comment]
Good luck for that.

**Comment by MrDarkPrince** [comment]
🙄

**Comment by KHarishDev** [comment]
> Good luck for that.

`Arigato Sensei`

**Comment by SOME-1HING** [comment]
> 

I mean really good luck, cuz it you are gonna get bombarded at the current state of ptbv20.

**Comment by KHarishDev** [comment]
> > 
> 
> I mean really good luck, cuz it you are gonna get bombarded at the current state of ptbv20.

damn

**Comment by SOME-1HING** [comment]
> > > 
> > 
> > 
> > I mean really good luck, cuz it you are gonna get bombarded at the current state of ptbv20.
> 
> damn

Fastest reply in the world
